version: 2.1

parameters:
  package:
    default: 'root'
    type: enum
    enum: ['root', 'backend', 'frontend']

jobs:
  foo:
    executor: default

    steps:
      - run:
          name: List files << pipeline.parameters.package >>
          command: ls -l

workflows:
  version: 2

  main:
    jobs:
      - foo
